### ISSUE TITLE
Fix API bugs

### ISSUE THREAD

**Issue by fraknoiadam** [a-gondolkodas-orome/durer-aion#76]
There are a lot of bugs:
- [ ] #97
- [x] If someone has already started a game (and it is FINISHED), you can start the game again. (The button is disabled, but the API point not. So if someone did not refreshed his browser in another computer, his button is not disabled, so he can start a new game. This happened this year with one team.) Expected behaviour: sends an error, and jumps to the current game.
- [ ] Over time point management is inconsistent #77 
- [ ] getTime endpoint is flawed possibly #67 

The following two bugs are also related to #97, so I make them complete here.
- [x] If someone has already started a game (and it is IN PROGRESS), you get an error and it stays in HOME. Expected behaviour: jump to the current game.
- [x] Strategy reset state api did not worked. It returns a new state, but not updates the teamstate
- [x] Admin endpoint reset-strategy is not working  #71

**Comment by czeildi** [comment]
Closing as it now just duplicates 97, the others have been fixed
